{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "1da1b700-b176-4aee-ba3d-2bc623bd0972",
   "metadata": {},
   "outputs": [],
   "source": [
    "import json\n",
    "import pandas as pd\n",
    "import re\n",
    "from datetime import datetime\n",
    "\n",
    "#Converts json to a list\n",
    "with open('transaction-data-adhoc-analysis.json') as f:\n",
    "    data = json.load(f)\n",
    "transactionitems=[]\n",
    "product = []\n",
    "udata = pd.read_json('transaction-data-adhoc-analysis.json', orient='column')\n",
    "df = pd.DataFrame(udata)\n",
    "\n",
    "for index, row in df.iterrows(): # seperates the groups of purchases into rows \n",
    "    transaction = row['transaction_items']\n",
    "    date = row['transaction_date']\n",
    "    item = transaction.split(\";\") #makes a dictionary for each group of items\n",
    "    for i in range(0,len(item)): #splits each item bought from its group and adds a date component\n",
    "        itemtobeadded = item[i] +',' + date\n",
    "        transactionitems.append(itemtobeadded)   \n",
    "\n",
    "#splits purchases into columns by Brand, Name, and Quantity\n",
    "for v in range(0, len(transactionitems)):\n",
    "    fitem = transactionitems[v].split(',')\n",
    "    product.append(fitem)\n",
    "\n",
    "#creates new dataframe for brand name, product name, quantity, and date\n",
    "ff = pd.DataFrame(product,columns = [\"Brand Name\", \"Product Name\", \"Quantity\", \"Date\"])\n",
    "\n",
    "#iterates through every item in column Quantity and removes all elements that is not within 0-9\n",
    "for y in range(len(ff['Quantity'])):\n",
    "    ff.loc[y, 'Quantity'] = re.sub('[^0-9]','',(str(ff.loc[y, 'Quantity'])))\n",
    "\n",
    "#converts to int column 'quantity'\n",
    "ff[\"Quantity\"] = ff[\"Quantity\"].astype(int)\n",
    "\n",
    "#gets the month component of the date of each transaction\n",
    "def gmonth(Date):\n",
    "    datem = datetime.strptime(Date, \"%Y/%m/%d\")\n",
    "    return datem.month\n",
    "ff[\"Date\"] = ff[\"Date\"].apply(gmonth)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "d6f75557-f4b0-4017-8ba9-780c487b65e3",
   "metadata": {},
   "outputs": [],
   "source": [
    "fdf = pd.DataFrame()\n",
    "\n",
    "#prices of each item\n",
    "prices = [1299,1500,150,799,1990,199,500]\n",
    "\n",
    "#return the quantity of each item per month\n",
    "for i in range(1,7):\n",
    "    month = ff.loc[ff[\"Date\"] == i]\n",
    "    month.groupby(['Product Name']).sum().squeeze().drop(\"Date\", axis= 1)\n",
    "    fdf[i] = month.groupby(['Product Name']).sum().squeeze().drop(\"Date\", axis= 1)\n",
    "\n",
    "#Quantity of each item per month\n",
    "ChicharonQ = fdf.iloc[0]\n",
    "VitaminsQ = fdf.iloc[1]\n",
    "WormsQ = fdf.iloc[2]\n",
    "KimchiQ = fdf.iloc[3]\n",
    "MilkQ = fdf.iloc[4]\n",
    "OrangeQ = fdf.iloc[5]\n",
    "VegetablesQ = fdf.iloc[6]\n",
    "\n",
    "#Multiplies each quantity to the price of each item\n",
    "Chicharon = fdf.iloc[0] * prices[0]\n",
    "Vitamins = fdf.iloc[1] * prices[1]\n",
    "Worms = fdf.iloc[2] * prices[2]\n",
    "Kimchi = fdf.iloc[3] * prices[3]\n",
    "Milk = fdf.iloc[4] * prices[4]\n",
    "Orange = fdf.iloc[5] * prices[5]\n",
    "Vegetables = fdf.iloc[6] * prices[6]\n",
    "\n",
    "\n",
    "itemcount = [ChicharonQ, VitaminsQ, WormsQ, KimchiQ, MilkQ, OrangeQ, VegetablesQ]\n",
    "itemcountframe = pd.DataFrame(itemcount)\n",
    "itemsales = [Chicharon, Vitamins, Worms, Kimchi, Milk, Orange, Vegetables]\n",
    "itemsalesframe = pd.DataFrame(itemsales)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "dbee3c57-6c5f-4edb-8be9-924128d7abef",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>1</th>\n",
       "      <th>2</th>\n",
       "      <th>3</th>\n",
       "      <th>4</th>\n",
       "      <th>5</th>\n",
       "      <th>6</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Beef Chicharon</th>\n",
       "      <td>9665</td>\n",
       "      <td>10001</td>\n",
       "      <td>9816</td>\n",
       "      <td>9890</td>\n",
       "      <td>10028</td>\n",
       "      <td>9902</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Gummy Vitamins</th>\n",
       "      <td>9681</td>\n",
       "      <td>9980</td>\n",
       "      <td>10145</td>\n",
       "      <td>9842</td>\n",
       "      <td>9948</td>\n",
       "      <td>9980</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Gummy Worms</th>\n",
       "      <td>9559</td>\n",
       "      <td>9996</td>\n",
       "      <td>9986</td>\n",
       "      <td>10043</td>\n",
       "      <td>9801</td>\n",
       "      <td>9934</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Kimchi and Seaweed</th>\n",
       "      <td>9676</td>\n",
       "      <td>9949</td>\n",
       "      <td>9967</td>\n",
       "      <td>9921</td>\n",
       "      <td>9773</td>\n",
       "      <td>10104</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Nutrional Milk</th>\n",
       "      <td>9727</td>\n",
       "      <td>9691</td>\n",
       "      <td>9876</td>\n",
       "      <td>9786</td>\n",
       "      <td>9881</td>\n",
       "      <td>9767</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Orange Beans</th>\n",
       "      <td>9774</td>\n",
       "      <td>10037</td>\n",
       "      <td>9611</td>\n",
       "      <td>9914</td>\n",
       "      <td>9964</td>\n",
       "      <td>10106</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Yummy Vegetables</th>\n",
       "      <td>9959</td>\n",
       "      <td>10256</td>\n",
       "      <td>9896</td>\n",
       "      <td>9861</td>\n",
       "      <td>9735</td>\n",
       "      <td>9722</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                       1      2      3      4      5      6\n",
       "Beef Chicharon      9665  10001   9816   9890  10028   9902\n",
       "Gummy Vitamins      9681   9980  10145   9842   9948   9980\n",
       "Gummy Worms         9559   9996   9986  10043   9801   9934\n",
       "Kimchi and Seaweed  9676   9949   9967   9921   9773  10104\n",
       "Nutrional Milk      9727   9691   9876   9786   9881   9767\n",
       "Orange Beans        9774  10037   9611   9914   9964  10106\n",
       "Yummy Vegetables    9959  10256   9896   9861   9735   9722"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "itemcountframe"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "c3e08bca-d359-4349-bc25-d86d86d47f95",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>1</th>\n",
       "      <th>2</th>\n",
       "      <th>3</th>\n",
       "      <th>4</th>\n",
       "      <th>5</th>\n",
       "      <th>6</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Beef Chicharon</th>\n",
       "      <td>12554835</td>\n",
       "      <td>12991299</td>\n",
       "      <td>12750984</td>\n",
       "      <td>12847110</td>\n",
       "      <td>13026372</td>\n",
       "      <td>12862698</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Gummy Vitamins</th>\n",
       "      <td>14521500</td>\n",
       "      <td>14970000</td>\n",
       "      <td>15217500</td>\n",
       "      <td>14763000</td>\n",
       "      <td>14922000</td>\n",
       "      <td>14970000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Gummy Worms</th>\n",
       "      <td>1433850</td>\n",
       "      <td>1499400</td>\n",
       "      <td>1497900</td>\n",
       "      <td>1506450</td>\n",
       "      <td>1470150</td>\n",
       "      <td>1490100</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Kimchi and Seaweed</th>\n",
       "      <td>7731124</td>\n",
       "      <td>7949251</td>\n",
       "      <td>7963633</td>\n",
       "      <td>7926879</td>\n",
       "      <td>7808627</td>\n",
       "      <td>8073096</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Nutrional Milk</th>\n",
       "      <td>19356730</td>\n",
       "      <td>19285090</td>\n",
       "      <td>19653240</td>\n",
       "      <td>19474140</td>\n",
       "      <td>19663190</td>\n",
       "      <td>19436330</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Orange Beans</th>\n",
       "      <td>1945026</td>\n",
       "      <td>1997363</td>\n",
       "      <td>1912589</td>\n",
       "      <td>1972886</td>\n",
       "      <td>1982836</td>\n",
       "      <td>2011094</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Yummy Vegetables</th>\n",
       "      <td>4979500</td>\n",
       "      <td>5128000</td>\n",
       "      <td>4948000</td>\n",
       "      <td>4930500</td>\n",
       "      <td>4867500</td>\n",
       "      <td>4861000</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                           1         2         3         4         5         6\n",
       "Beef Chicharon      12554835  12991299  12750984  12847110  13026372  12862698\n",
       "Gummy Vitamins      14521500  14970000  15217500  14763000  14922000  14970000\n",
       "Gummy Worms          1433850   1499400   1497900   1506450   1470150   1490100\n",
       "Kimchi and Seaweed   7731124   7949251   7963633   7926879   7808627   8073096\n",
       "Nutrional Milk      19356730  19285090  19653240  19474140  19663190  19436330\n",
       "Orange Beans         1945026   1997363   1912589   1972886   1982836   2011094\n",
       "Yummy Vegetables     4979500   5128000   4948000   4930500   4867500   4861000"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "itemsalesframe"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
